### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by cooper667** [percy/percy-selenium-js#190]
The current published npm version is 1.0.0 and there's a few changes in here since then (mainly the selenium-webdriver dependency), so should a new release be created?

**Comment by Robdel12** [comment]
Hey @cooper667! Sorry for the delay on this, you're right it was time for a fresh release to update the peer dep. v1.0.1 is out now: https://github.com/percy/percy-selenium-js/releases/tag/v1.0.1
