### ISSUE TITLE
[percy] Unsupported Percy CLI version, disabling snapshots is seen when using selenium-webdriver

### ISSUE THREAD

**Issue by SherBhachuOnFido** [percy/percy-selenium-js#77]
I have a simple test that does the following...

```js
...
const percySnapshot = require('@percy/selenium-webdriver')
...
it('should verify website title', async () => {
  driver.get(`${localhostUrl}?language=${lang}`)
  await percySnapshot(driver, 'Some Demo Homepage')
  const title = driver.getTitle()
  expect(title).to.equal('Some Title ')
})
```

I have followed the instructions here, https://docs.percy.io/docs/selenium-for-javascript , in regards to npm setup and such.

I am a little confused as to what is happening. 

The tests run all ok ...

```shell
...
Tests finished
Killing mock server
...
[percy] stopping percy...
[percy] waiting for 0 snapshots to complete...
[percy] done.
```

**Comment by Robdel12** [comment]
👋🏼 Hey @SherBhachuOnFido thanks for the issue! When this is logged:

```
[percy] waiting for 0 snapshots to complete...
```

That usually means `percySnapshot` wasn't called in the test run. What does the test `should verify website title` log when tests run? Also, I think this would be a better test. Once `percySnapshot` is called, we're going to capture that exact page state (half loaded, not loaded, etc). 

```js
const percySnapshot = require('@percy/selenium-webdriver')

it('should verify website title', async () => {
  await driver.get(`${localhostUrl}?language=${lang}`)
  const title = await driver.getTitle()
  expect(title).to.equal('Some Title ')
  await percySnapshot(driver, 'Some Demo Homepage')
});
```

Also, I noticed there are two missing `awaits` in your example (`await driver.get` & `await driver.getTitle`). For example, this is in our example app: https://github.com/percy/example-percy-selenium-javascript/blob/master/tests/test.js#L30-L34 :D 


---

As for the second comment, that's expected. Percy downloads a specific version of Chromium to do asset discovery in. This can be skipped by providing a path to your own browser executable: https://docs.percy.io/docs/skipping-asset-discovery-browser-download
